### ISSUE TITLE
Version 1.0.2-1 displaying the wrong tray icon

### ISSUE THREAD

**Issue by ViBE-HU** [andrebrait/prime-indicator#20]
I'm on Unity and noticed that the icon shows always Intel since last update. I checked a few times but no luck.

![indicator](https://cloud.githubusercontent.com/assets/640109/19946233/ca614a94-a143-11e6-851f-f8eb2255ecf8.jpg)

**Comment by andrebrait** [comment]
That's weird. Perhaps something happened during the packaging. I'm gonna check with @hotice. The difference between 1.0.0 and 1.0.2 shouldn't have made this happen.

**Comment by andrebrait** [comment]
Did you change anything other than that? Can you try the color option?

Turning Secure Boot on has some weird effects on Optimus laptops and Linux. Do you know if you enabled it?

**Comment by ViBE-HU** [comment]
I corrected the version number. So I did not changed anything. It works well, changing the VGAs but displaying incorrectly. I never touched the configuration file. I'm using the default settings.

**Comment by andrebrait** [comment]
Can you please the changing the iconset option in the file ~/.config/prime-indicator/prime-indicator.cfg to the color option? It's very weird. It would only do that if it found an icon for the word NVIDIA in your icon theme that would correspond to the intel icon... I'm reading things here again to see if I find the error.

**Comment by andrebrait** [comment]
Found it. It's weird. I'm trying to find the commit that changed it.

**Comment by andrebrait** [comment]
Fixed it.

It should be up to the PPA in a few days. However, if you want it fixed right away, download the 1.0.3 code from here:

https://github.com/andrebrait/prime-indicator/archive/1.0.3.zip

Then extract it to somewhere and run the setup script as root. It won't affect the packaging in your distro. When it updates through apt-get it will overwrite the files.

**Comment by ViBE-HU** [comment]
Strange. I changed it from `theme-default` to `color` as you asked and now showing correctly.

**Comment by andrebrait** [comment]
Not strange at all. The `theme-default` option falls back to the color option when no icon is found. It was happening to you, but I had screwed the fall back selection and it always ended up selecting Intel. The `color` option was untouched and it worked ok.

**Comment by ViBE-HU** [comment]
Oh thanks for your fast reaction. So that's why no monochrome theme been displayed at all.

**Comment by andrebrait** [comment]
You're welcome!

If it's failing to detect the proper icons, you can set your own custom color in the config file using the `custom(#AAAAAA)` code, where AAAAAA is the 6-digit hex RGB representation of the color you want. You can use this [HTML Color Picker](http://www.w3schools.com/colors/colors_picker.asp) to pick the color you want from the pallete and copy its Hex code. It will start using the color when you log out and then log in again.

**Comment by ViBE-HU** [comment]
Clear. Cool feature but I'm absolutely satisfied with your original themes and with the whole application. Hope we never get more serious issues than this :D

**Comment by andrebrait** [comment]
Let's hope not hahaha. A guy reported an issue with GNOME that wouldn't let the computer start after installing prime-indicator, but I suspect he installed it along with bumblebee, which is known to cause these errors.

When you confirm it has been fixed, please tell me so I can close the issue :)

**Comment by ViBE-HU** [comment]
Somehow the fix just partially working for me. I installed it and set back to `theme-default` but it show the coloured version.

**Comment by andrebrait** [comment]
It seems it's working ok (the fallback was the broken part) but it still can't find icons for nvidia or intel in your Icon theme. It's up for the theme to provide them.

It works something like this:
- Hey GTK! Does the user's theme have some icon named something-intel-something?
- Erm.... let me look for it... nope, there is not.
- Ok, I'm gonna use my own icon then. Thanks!
- You're welcome, application ;)

So, if the theme doesn't provide the icon, it just uses the colored icons. That's where the symbolic option comes into play, as it tries to guess what color should the icons have based on your theme's settings. It doesn't work very well, however... and that's why I implemented the custom option, so the user set the color he wants and that's it. 

The bug was that my application had gone a bit nuts and used the intel icon regardless of which GPU was being used, after talking to the GTK and receiving the 'nope' answer.

**Comment by andrebrait** [comment]
Fixed in version 1.0.3
